allowBuilds:
  '@parcel/watcher': true
  es5-ext: false
  gifsicle: set this to true or false
  mozjpeg: set this to true or false
  optipng-bin: set this to true or false

overrides:
  lodash: ^4.17.24
  minimatch@<3.1.4: ^3.1.4
  node-uuid: ^1.4.8
  postcss@<8.5.26: ^8.5.26
  uuid: ^11.1.1
